### ISSUE TITLE
Code generation fails (known java version incompatibility?)

### ISSUE THREAD

**Issue by gunnarx** [gunnarx/build-common-api-cpp-native#7]
The following failure occurs on a modern installation, in this case Fedora 29:
```
java -version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7, mixed mode, sharing)
```

Once the installation script gets to the code-generation stage (code generators have been downloaded).  In fact, it happens even if you check the version:

```
project/cgen/commonapi-generator/commonapi-generator-linux-x86_64 --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.storage.FrameworkExtensionInstaller (file:/home/user/devel/GENIVI/franca_ara_integration/dependencies/build-common-api-cpp-native/project/cgen/commonapi-generator/plugins/org.eclipse.osgi_3.10.2.v20141020-1740.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.storage.FrameworkExtensionInstaller
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The text still says warning, but this also throws a dialog window which calls it an error.

When the script runs it will further report:
```
FAILED!  Message follows:
Command ./cgen/commonapi-generator/commonapi-generator-linux-x86_64 -sk ./fidl/HelloWorld.fidl failed -- check above for details
```
(and so on...)

That code generation failed is of course also later noticed and reported by the main script:

```
FAILED!  Message follows:
Expected result file HelloWorldDBusDeployment.cpp not present (not built)!
```
(repeated)

This seems to be a known issue.  With openjdk-11 however, an error is reported as opposed to a warning, and no code is generated.  

Assume this is just the next step of previously known java version incompatibility.  This version of the code generators were made for Java 8, apparently. 

Upstream issue:
https://github.com/GENIVI/capicxx-core-tools/issues/15

**Solution**: I have no other good solution but to ensure the installed java version is java 8.

I'd be happy to receive a patch from someone, that sets up a local java installation as part of the script so that the system does not need to downgrade its main installation.

**Comment by Dellamoresteven** [comment]
Did it work for you when you used java 8 @gunnarx ? I tried to do the tutorial manually but I ran into the same problem this script is having. I tried to go down to java 8 but it still didnt work.

**Comment by gunnarx** [comment]
What was the problem after you downgraded?  Can you clarify the error please.

**Comment by Dellamoresteven** [comment]
Sorry! I received the same problem, meaning "The text still says warning, but this also throws a dialog window which calls it an error.".
The error log is the exact same error as before i used java8. I am a x86_64 Ubuntu 18.04.

**Comment by Dellamoresteven** [comment]
So I was able to get past that part. The Dbus executable are are created seem to work just fine. The SOMEIP executable on the other hand are not built. There is an error message once the script tryts to make. 

`
[  5%] Linking CXX executable HelloWorldSomeIPService
/usr/bin/ld: warning: libboost_filesystem.so.1.64.0, needed by //projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0, not found (try using -rpath or -rpath-link)
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::read_symlink(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::dir_itr_close(void*&, void*&)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::system_complete(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::path::filename() const'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::current_path(boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::path::parent_path() const'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::space(boost::filesystem::path const&, boost::system::error_code*)'
//projects/scriptv2/autoscript/build-common-api-cpp-native/install/lib/libboost_log.so.1.64.0: undefined reference to `boost::filesystem::detail::equivalent(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
CMakeFiles/HelloWorldSomeIPService.dir/build.make:198: recipe for target 'HelloWorldSomeIPService' failed
make[2]: *** [HelloWorldSomeIPService] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/HelloWorldSomeIPService.dir/all' failed
make[1]: *** [CMakeFiles/HelloWorldSomeIPService.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by gunnarx** [comment]
Maybe this was a bug, I'm not sure.  It could be that the build environment had boost installed also in a central location.   Maybe commit 90a4555d91fe63d1d7aa503478ec8f3e53af7383 helps.

In any case, I have made a few changes, so please try the latest.  Please be aware that this script is just a friendly helper, and not a high priority project for me so I do not have time to give a lot of support.

Just to be confident in the behavior I set up for myself a repeatable setup by running in docker.  You can try the run-in-docker.sh script to repeat it.  That repeatable setup "proves" that the code generation steps work with java 8.  I chose a base distro of Ubuntu 16.04 because it seems to have this version by default and so I had to do nothing special.  After everything is built the container contained this java version:

```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

Everything now builds OK for me, including vSOMEIP when using the run of run-in-docker.sh.  In that setup I now get a runtime error for the generated program (HelloWorld **client** for D-Bus, the server seems OK though) but I won't put time into debugging that now.  The SOMEIP variant of client/server test works.  Of course I should note that the docker container was not running as privileged so if any program tries some particular kernel calls that need special permissions then these could fail (just a thought).

You could start with updating everything and see if that helps.  If there is still trouble in compiling on your own machine, try to compare your build environment to the repeatable docker setup.

Hope this helps.
