### ISSUE TITLE
SOME/IP lib not found

### ISSUE THREAD

**Issue by diasdm** [gunnarx/build-common-api-cpp-native#8]
Hello,

While running the SOME/IP examples I got this error:

```
$ ./project/build/HelloWorldSomeIPClient 
[2019-07-22 15:42:30.318990] [0x00007f5e2b3cbb80] [error]   Loading failed: (libvsomeip-cfg.so.2: cannot open shared object file: No such file or directory)
Service Discovery module could not be loaded!
```

Doing `$ export LD_LIBRARY_PATH="<PATH_TO_REPO>/vsomeip/build"` fixed it. Maybe this should be added to the script?

Thank you.

**Comment by gunnarx** [comment]
Sorry for not replying/closing this issue previously.

I added a comment to use LD_LIBRARY_PATH to the readme quite a while ago, I guess triggered by your ticket probably.

A lot has been rewritten in recent updates I made, including to properly install all the built libraries into a separate subdirectory named **install/lib** so  if LD_LIBRARY_PATH still needs to be set (I usually don't have to) it should in any case be set to that directory now.

Thanks a whole lot for your input.  Appreciated, even if the question was unanswered (and the project was unmaintained) for the last year.
